012 new role
Wojciech-Skarbek-K/groupA-backend pull request #28
Opened 2022-07-20 08:56 UTC by ConorGallagher1

2022-07-20 10:19 UTC, shaunganley requested changes
few small comments, good work on this

2022-07-20 10:19 UTC, shaunganley commented on src/main/java/org/kainos/groupA/controller/AddJobRoleController.java
> +            if (addJobRoleValidator.isValidJobRole(jobRole)) {
move this if statement to the service class so you can easily unit test it

2022-07-20 10:19 UTC, shaunganley commented on src/main/java/org/kainos/groupA/services/AddJobRoleService.java
> +    public AddJobRoleDao addJobRoleDao;
don't think this needs to be public

2022-07-20 10:19 UTC, shaunganley commented on src/test/java/org/kainos/groupA/integration/AddJobRoleIntegrationTest.java
> +        jobRole.setRole_name(null);
shouldn't a null role name be a bad request (400) rather than a 500?

2022-07-20 10:19 UTC, shaunganley commented on src/test/java/org/kainos/groupA/validator/AddJobRoleValidatorTest.java
> +    public void isValidJobRole_shouldThrowInvalidJobRoleException_whenRoleNameTooLong() {
you're missing a test for returns true

2022-07-21 08:25 UTC, Wojciech-Skarbek-K approved these changes

2022-07-21 10:15 UTC, shaunganley requested changes
small changes

2022-07-21 10:15 UTC, shaunganley commented on src/main/java/org/kainos/groupA/controller/AddJobRoleController.java
> +                } catch (SQLException | NullPointerException | InvalidJobRoleException e) {
400 errors are for user input errors, SQLException should return 500

2022-07-21 10:15 UTC, shaunganley commented on src/test/java/org/kainos/groupA/service/AddJobRoleServiceTest.java
> +
needs test for isValidJobRole returns false

2022-07-21 12:26 UTC, shaunganley approved these changes

2022-07-21 12:57 UTC, merged